save session
wolox-training/dq-react-native pull request #18
Opened 2020-10-30 22:03 UTC by DiegoQuiros94

trello card: https://trello.com/c/iflRuvLn/41-persistencia-de-sesi%C3%B3n

screencast:
![persist session iphone 11](https://user-images.githubusercontent.com/37076806/97760641-62f3ad80-1ae2-11eb-9d10-14c5878920ae.gif)

known issues:
i get a warning saying something about animations but i have no clue what it means:
![image](https://user-images.githubusercontent.com/37076806/97760703-84ed3000-1ae2-11eb-90b9-4fe74a1927e2.png)

2020-11-02 23:07 UTC, sfernandez11 requested changes
Good work! Some comments, please check the acceptance criteria of this [card](https://trello.com/c/iflRuvLn/41-persistencia-de-sesi%C3%B3n) because you forgot to do some of them

2020-11-02 23:07 UTC, sfernandez11 commented on src/app/screens/LoginScreen/index.tsx
> +  }, [dispatch]);
Move the `rehydrate` function to the `AppNavigator` because in this component you handle the App's stack logic. Also, you can add some `initialLoading` logic to show while the app is rehydrating.

2020-11-02 23:07 UTC, sfernandez11 commented on src/constants/localStorage.ts
> +
Move this file to the `services` folder, `LocalStorage` is an internal service.

2020-11-02 23:07 UTC, sfernandez11 commented on src/constants/localStorage.ts
> +const tokenKey = 'WBOOKS_TOKEN';
Use: `AUTH_TOKEN (in mayus for constants) = '@WBOOKS:AUTH_TOKEN';`

2020-11-02 23:07 UTC, sfernandez11 commented on src/redux/auth/actions.ts
>  import { Dispatch } from 'redux';
Sort imports

2020-11-02 23:07 UTC, sfernandez11 commented on src/redux/auth/actions.ts
> +      dispatch({ type: actions.LOG_IN_SUCCESS, payload: token });
No, this is wrong. You must create and use another ACTION for this logic

2020-11-02 23:07 UTC, sfernandez11 commented on src/redux/auth/reducer.ts
> +      storeToken(action.payload);
Don't use external functions in the `reducer`, move it to the `actions` file

2020-11-03 14:03 UTC, DiegoQuiros94 commented on src/app/screens/LoginScreen/index.tsx
> +  }, [dispatch]);
is it worth showing a loading state? isn't the localstorage access almost instantaneous? (even though it's an async operation)

2020-11-04 16:17 UTC, sfernandez11 requested changes
Last comments...

2020-11-04 16:17 UTC, sfernandez11 commented on src/services/localStorage.ts
> +
Check file name: Typo `src/services/localStorage.ts` => `src/services/LocalStorage.ts`

2020-11-04 16:17 UTC, sfernandez11 commented on src/redux/auth/reducer.ts
> +  sessionLoading: false
No, initially "sessionLoading" should be "true" because the application is mounting/loading and waiting for the AsyncStorage in this case. When the rehydration process is finished, the `sessionLoading` should be` false`

2020-11-04 16:17 UTC, sfernandez11 commented on src/redux/auth/reducer.ts
> +      return { ...state, sessionLoading: false };
These two actions are not necessary if you initialize the `sessionLoading: true` as I said in the previous comment. `action.payload` can be: `headers` (has previous session) or null (initial state, check `getHeaders` in `LocalStorage` service)

2020-11-04 16:17 UTC, sfernandez11 commented on src/redux/auth/reducer.ts
> +    case loginActions.SESSION_RECOVERED:
`SESSION_RECOVERED` => `SESSION_RECOVER`

2020-11-04 16:17 UTC, sfernandez11 commented on src/redux/auth/actions.ts
> +  SESSION_NOT_RECOVERED: '@@AUTH/SESSION_NOT_RECOVERED'
Keep only: `SESSION_RECOVER: '@@AUTH/SESSION_RECOVER'`

2020-11-04 16:17 UTC, sfernandez11 commented on src/redux/auth/actions.ts
>    }
I think we can improve this function, try this:
```
  rememberUser: () => async (dispatch: Dispatch) => {
    const headers = await getHeaders();
    if (headers) api.setHeaders(headers); // You forgot this
    dispatch({ type: actions.SESSION_RECOVER, payload: headers }); // headers can be authHeaders or null
  }
```

2020-11-04 16:17 UTC, sfernandez11 commented on src/app/components/AppNavigator/index.tsx
> +          initialParams={{ text: 'Loading...' }}
This solution works but we should talk about it, I think you are overthinking the solution.

2020-11-04 17:43 UTC, DiegoQuiros94 commented on src/services/localStorage.ts
> +
I don't know why it's showing in lowercase here, it seems okay in my project 🤔

2020-11-04 21:22 UTC, sfernandez11 commented on src/services/localStorage.ts
> +
Done, it's a github bug

2020-11-04 21:25 UTC, sfernandez11 approved these changes
Nice work 🥇

2020-11-04 21:26 UTC, sfernandez11 commented on src/app/components/AppNavigator/index.tsx
> +          initialParams={{ text: 'Loading...' }}
TODO => :no-vimo:

2020-11-05 17:24 UTC, merged